# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0002_auto_20190917_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(max_length=500),
        ),
    ]
