# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0003_auto_20190917_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, unique=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='meta_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vids.Video'),
        ),
    ]
