# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0005_auto_20190918_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(max_length=500)),
                ('meta_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vids.Video')),
            ],
        ),
    ]
