# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0006_videometadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videometadata',
            name='meta_title',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='VideoMetadata',
        ),
    ]
