# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vids', '0007_auto_20190918_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('categories', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, unique=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(max_length=500)),
                ('meta_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vids.Video')),
            ],
        ),
    ]
