# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0008_video_videometadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
