# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0009_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
