# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0010_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.IntegerField(default=1),
        ),
    ]
