# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0011_auto_20190920_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
