# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0013_auto_20190920_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_val', models.CharField(max_length=500)),
            ],
        ),
    ]
